[project]
name = "acpagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beeai-sdk>=0.0.14",
]

[project.scripts]
acp-agent = "acpserver.server:main"
